### ISSUE TITLE
Is it possible to visualise a Station names? 

### ISSUE THREAD

**Issue by Pogadi** [juliuste/transit-map#6]
Hi, I like your project, great work. But I would like to know, whether there is a possibility to add a feature for printing name of the station to every node.

**Comment by juliuste** [comment]
Sorry for the late reply, unfortunately this is not (easily) possible as of now. The only way this could work at the moment would be to model the labels as short little lines with a length of one stop departing from each station and replacing them with the text afterwards, but this would probably increase the computing time dramatically. I have this in the back of my mind, though, and will re-open this issue once I found a way to do it.
